#!/bin/bash
PATH=$PATH:/usr/local/bin:~/Library/Android/sdk/platform-tools:~/Library/Android/sdk/tools
export ANDROID_HOME=~/Library/Android/sdk

if [[ $# -eq 0 ]] ; then
    echo '    usage:  build {id} {appName} {version} {build}'
    echo '  example:  build "app"  "School Loop" "2.0.0" "199"'
    exit 1
fi

ID=$1
NAME=$2
VERSION=$3
BUILD=$4

npm install
bower install
rm -rf tmp/*.js
./release/create-app "$ID"
gulp init --id "$ID" --name "$NAME" --version "${VERSION}" --build "${BUILD}"
gulp --id "$ID" --name "$NAME" --version "${VERSION}" --build "${BUILD}"
cd ./app
cordova prepare
