#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo '    usage:  deploy {appId} {displayName} {version} {build}'
    echo '  example:  deploy "app" "SchoolLoop" "2.0.0" "199"'
    exit 1
fi

ID=$1
APP_NAME=$2
VERSION=$3
BUILD=$4

cp platforms/android/build/outputs/apk/android-release.apk release/${APP_NAME}-${VERSION}-${BUILD}.apk
mv release/${APP_NAME}-*.ipa release/${APP_NAME}-${VERSION}-${BUILD}.ipa
mv release/${APP_NAME}-*.zip release/${APP_NAME}-${VERSION}-${BUILD}-dSYM.zip
cp release/*.apk /Users/tombu/Downloads/builds/${ID}/
cp release/*.ipa /Users/tombu/Downloads/builds/${ID}/
cp release/${APP_NAME}-${VERSION}-${BUILD}.ipa release/${APP_NAME}-${VERSION}.ipa
rm -f release/${APP_NAME}-*