#!/bin/bash

APP_ID=$1
VERSION=$2

PATH=$PATH:/usr/local/bin

echo "Uploading change file for $APP_ID"
gulp upload --id $APP_ID --build $VERSION

cd ./app
echo "Deploying files for hot code push"
cordova-hcp deploy
